export const AllMasseges = {
     SeeYouSoon : "See You Soon :)",
     EmailAndPass : "Email And PassWord Are Requireds Feelds",
     OneIsIncorrect : <div>Please check your Email, and Password and try again </div>,
     GladUBack : "Glad You're Back",
     BusinessNameError :"Business Name Is A Required Feeld",
     BusinessDescriptionError :"Business Description Is A Required Feeld",
     BusinessAddressError :"Business Address Is A Required Feeeld",
     BusinessPhoneError1 :"Business Phone Number Is A Required Feeld",
     BusinessPhoneError2 :"Business Phone Number Must be 10 Digits!",
     BusinessPhoneError3 :"Business Phone Number Cant be more then 10 Digits!",
     EPN_Error :"Email Password and Name are A Requireds Feelds",
     PassChecked_Error : "You must confirm Password to continue ",
     User_Error :"User Exists In The system",
     PassLength :<div>Password length must be between : <br/> 6-8 Letters </div>,
     Successfully_Registered_Simple : "You Have Successfully Registered",
     Successfully_Registered_Busines : "You have successfully completed the registration step",
     Pass_Error : "Password Must contain one Digit, one Uppercase letter and one Lowercase letter",
     Name_Error : <div>Name length must be between : <br/> 3-15 Letters</div>,
     SuccessfullyCard : "Card created Successfully",
     SameCard : <div> This card already exists in the system! <br/> Please enter different details</div>,
    Pass_Confirm :<div> Passwords not match ! <br/>  Plz try again :) </div>,
    };
